### ISSUE TITLE
放到服务器上运行出错，求教！

### ISSUE THREAD

**Issue by swimly** [kilingzhang/NeteaseCloudMusicApi#2]
Fatal error: Uncaught InvalidArgumentException: The directory "C:\WINDOWS" is not writable. in E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\doctrine\cache\lib\Doctrine\Common\Cache\FileCache.php:92 Stack trace: #0 E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\doctrine\cache\lib\Doctrine\Common\Cache\FilesystemCache.php(37): Doctrine\Common\Cache\FileCache->__construct('C:\\WINDOWS', '.doctrinecache....', 2) #1 [internal function]: Doctrine\Common\Cache\FilesystemCache->__construct('C:\\WINDOWS', '.doctrinecache....', 2) #2 E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\php-di\php-di\src\DI\Definition\Resolver\ObjectCreator.php(138): ReflectionClass->newInstanceArgs(Array) #3 E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\php-di\php-di\src\DI\Definition\Resolver\ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array) #4 E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\php-di\php-di\src\DI\Definition\Resolver\Resolver in E:\User\Documents\Projects\NeteaseCloudMusicApi\vendor\doctrine\cache\lib\Doctrine\Common\Cache\FileCache.php on line 92

运行的时候报这个目录不能写，请问是什么原因造成的

**Comment by kilingzhang** [comment]
这个应该是c:windows那个目录没有读者权限吧😂
