### ISSUE TITLE
一半接口都失效了

### ISSUE THREAD

**Issue by cnstephen** [kilingzhang/NeteaseCloudMusicApi#5]
一半接口都失效了

**Comment by kilingzhang** [comment]
可以再试一下，测试了下，除了需要登录的接口其他的都是正常的。 登录接口也做了最新的支持。https://github.com/kilingzhang/NeteaseCloudMusicApi/commit/5fb7d8d3a793bc52495364ce24355e67a042943d

**Comment by kilingzhang** [comment]
> 一半接口都失效了

可以再试一下，测试了下，除了需要登录的接口其他的都是正常的。 登录接口也做了最新的支持。https://github.com/kilingzhang/NeteaseCloudMusicApi/commit/5fb7d8d3a793bc52495364ce24355e67a042943d
